server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  # Proxy API -> backend (service docker compose)
  location /api/ {
    proxy_pass http://etl-backend:8000/;
  }
}
